version: "3.8"
services:
  backend:
    container_name: cronops-backend
    build: .
    env_file:
      - .env
    ports:
      - "8090:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - cronops_net

  database:
    container_name: cronops-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./cronops-data:/var/lib/postgresql/data:rw
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

    networks:
      - cronops_net

networks:
  cronops_net:
