apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cronops
  template:
    metadata:
      labels:
        app: cronops
    spec:
      containers:
        - name: cronops
          image: nsahil992/cronops:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
