apiVersion: v1
kind: Service
metadata:
  name: cronops-service
spec:
  selector:
    app: cronops
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30100
      protocol: TCP